spring:
  application:
    name: esportLab
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  datasource:
    url: ${DB_URL:${DATABASE_URL:jdbc:postgresql://localhost:5432/esports}}
    username: ${DB_USER:esports}
    password: ${DB_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false
    out-of-order: true
  
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: ${DISCORD_CLIENT_ID}
            client-secret: ${DISCORD_CLIENT_SECRET}
            redirect-uri: ${DISCORD_REDIRECT_URI}
            scope: identify
            authorization-grant-type: authorization_code
        provider:
          discord:
            authorization-uri: https://discord.com/api/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/v10/users/@me
            user-name-attribute: id

server:
  port: ${PORT:8080}
  servlet:
    session:
      cookie:
        http-only: true
        secure: ${COOKIE_SECURE:false}
        same-site: none

app:
  base-url: ${APP_BASE_URL:http://localhost:8080}
  frontend:
    url: ${FRONTEND_URL:https://esportlab.run}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  jwt:
    secret: ${JWT_SECRET:mySecretKey1234567890123456789012345678901234567890}
    expiration-hours: ${JWT_EXPIRATION_HOURS:24}
  
  discord:
    bot-token: ${DISCORD_BOT_TOKEN:}
    webhook-url: ${DISCORD_WEBHOOK_URL:}
  
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME:}
    api-key: ${CLOUDINARY_API_KEY:}
    api-secret: ${CLOUDINARY_API_SECRET:}
  
  reminder:
    hours: ${REMINDER_HOURS:0,6,12,18}
    timezone: ${TIMEZONE:Europe/Berlin}
  
  team:
    min-players: ${MIN_PLAYERS:4}
    min-duration-minutes: ${MIN_DURATION_MINUTES:90}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.flywaydb: INFO

---
spring:
  config:
    activate:
      on-profile: dev
  
  jpa:
    show-sql: true
  
server:
  servlet:
    session:
      cookie:
        secure: false

---
spring:
  config:
    activate:
      on-profile: prod
  
  jpa:
    show-sql: false
    
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
  
server:
  servlet:
    session:
      cookie:
        secure: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.flywaydb: INFO
    run.esportLab: INFO