# Railway.app specific configuration
spring:
  config:
    activate:
      on-profile: railway
  
  datasource:
    url: ${DATABASE_URL}
    # Railway provides DATABASE_URL in the format: postgresql://user:pass@host:port/db
    # Spring Boot will parse this automatically
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false  # More forgiving for deployment
    out-of-order: true          # Allow out-of-order migrations
  
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: ${DISCORD_CLIENT_ID}
            client-secret: ${DISCORD_CLIENT_SECRET}
            redirect-uri: ${DISCORD_REDIRECT_URI}
            scope: identify
            authorization-grant-type: authorization_code

server:
  port: ${PORT:8080}
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
        same-site: none

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-hours: ${JWT_EXPIRATION_HOURS:24}
  frontend:
    url: ${FRONTEND_URL:https://esportlab.run}

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.flywaydb: INFO
    run.esportLab: INFO
    org.hibernate.SQL: ${LOG_SQL:false}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOG_SQL:false}